### ISSUE TITLE
Undefined local variable or method `logger'

### ISSUE THREAD

**Issue by zero20nemvp** [rack-app/rack-app-front_end#5] opened 2023-09-02 13:28 UTC
```
  class Sso < Rack::App
    get '/ok'
      'ok'
    end
  end
```

If you run this small app . it will raise an error.

![Screenshot 2023-09-02 at 16 22 18](https://github.com/rack-app/rack-app-front_end/assets/141216207/c08b86df-725e-4b03-b684-7907fb240688)

```
class App < Rack::App
    apply_extensions :logger    
    get '/ok'
      'ok'
    end
  end
```

this fixes it, the issues is caused by 

![Screenshot 2023-09-02 at 16 26 03](https://github.com/rack-app/rack-app-front_end/assets/141216207/e97be477-8502-4980-9edd-849ad4b59382)

is there a way to check for logger before we call it in the before block? or if you have a better solution .

**Comment by adamluzsi** [comment] 2023-09-03 11:01
Hello @vidtreonou,

I've created a repository to help investigate the issue you're facing. You can access it here: [Example for Vidtreonou on GitHub](https://github.com/rack-app/example-for-vidtreonou).

Interestingly, I wasn't able to replicate the issue you described. Would you mind giving it a try and seeing if you encounter the same problem? You might consider altering the code to recreate the issue you're experiencing.

Here's your invitation link to the repository: [GitHub Invitation](https://github.com/rack-app/example-for-vidtreonou/invitations).

Just a heads-up: The logger method is usually not meant to be used without its corresponding extension unless you've set up a custom logger method with a logging library that supplies the logger method.

Feel free to reach out if you encounter any issues in your environment. I've also included setup instructions within the repository for your convenience.

Cheers,
Adam

**Comment by adamluzsi** [comment] 2023-09-03 11:02
```bash
git clone git@github.com:rack-app/example-for-vidtreonou.git example-for-vidtreonou
cd example-for-vidtreonou

bundle install
bundle exec rackup
```

**Comment by zero20nemvp** [comment] 2023-09-03 11:12
sure can.

will get that done and let you know

**Comment by adamluzsi** [comment] 2023-09-03 19:00
What's intriguing is that the 'before' block in the extension is designed to run only when the extension itself is activated. This should, by default, include the logger method. So it's somewhat mystifying why you're encountering this issue—I'm not quite sure what's causing it.

My guess is that your API might have another endpoint, like "/auth/developer/callback," that calls the logger method. However, the class itself might not have access to the logger method, either because the extension isn't activated or there's no alternative solution providing it.

**Comment by zero20nemvp** [comment] 2023-09-05 02:21
Hey sorry for the delay getting back. 

ok I have cloned the project and ran the script.

<img width="926" alt="Screenshot 2023-09-05 at 05 18 40" src="https://github.com/rack-app/rack-app-front_end/assets/141216207/1265d1fe-9a6d-4d8f-8323-64658bf00562">

it works fine. 

I am using the app in a modular way.  so I will try an recreate the structure on a different branch .


thanks for the help

**Comment by zero20nemvp** [comment] 2023-09-05 02:32
I have pushed a branch called modular.

Given this

```
require "rack/app"
require "rack/app/front_end"

class Sso < Rack::App

   get '/ok' do
     'ok'
   end

end

class App < Rack::App

  apply_extensions :logger
  apply_extensions :front_end

   mount Sso, to: "/auth"

   get '/ok' do
     'ok'
   end
   
end

run App
```

when I run 


`bundle exec backup`

I get

<img width="926" alt="Screenshot 2023-09-05 at 05 27 08" src="https://github.com/rack-app/rack-app-front_end/assets/141216207/3423d6c1-698d-4d86-ba86-73bb94a2cdf2">

**Comment by zero20nemvp** [comment] 2023-09-05 02:49
Given this

```
require "rack/app"
require "rack/app/front_end"

class Sso < Rack::App
    apply_extensions :logger
   get '/ok' do
     'ok'
   end

end

class App < Rack::App

  apply_extensions :logger
  apply_extensions :front_end

   mount Sso, to: "/auth"

   get '/ok' do
     'ok'
   end
   
end

run App
```

when I run

bundle exec backup

I get

<img width="926" alt="Screenshot 2023-09-05 at 05 18 40" src="https://github.com/rack-app/rack-app-front_end/assets/141216207/e20d1bb3-bcb6-4992-a915-cd31e497af56">


I think I made the assumption that 

`apply_extensions :logger`

was only needed on the base app and not the mounted apps

can you please confirm that my asumption is indeed incorrect.

**Comment by zero20nemvp** [comment] 2023-09-05 02:51
for now I will check through the project and make sure. 

Thanks for time and help, much appreciated.

**Comment by adamluzsi** [comment] 2023-09-05 08:12
I can confirm that using `apply_extensions :logger` is intended for a specific class. It operates much like the `extend` and `include` module methods in Ruby, except it might perform both actions if an extension demands it.

Your observation is insightful. The current strategy to preload/eager-load the logger might not be the optimal approach. But, the scope where the 'before' block executes might be misaligned as well. I'll need to ponder this further.

Let's break down the root of the issue you identified, and I'd appreciate your perspective on potential solutions.

**The Issue:**
The 'before' block is set to execute prior to an endpoint being accessed and operates within the scope of that endpoint. The scenario you pinpointed is unique: the 'before' block utilizes an instance method from the class where it's defined. However, during execution, the block's scope shifted to the mounted application.

```ruby
class A < Rack::App
  get "/" do
    "Hello, world!"
  end
end

class B < Rack::App
  before { my_instance_method }

  def my_instance_method()
  end
  
  mount A, to: "/x" 
end

run B

# Accessing /x/ results in a no-method error 
```

**My Suggested Solution:**
I propose that the 'before' block should recognize the class in which it's established. Subsequently, the hook's execution should be adjusted to remain within the scope of the class where it was defined rather than switching to the class of the called endpoint.

Please let me know what you think. In the meantime, I proceed to make a few tests to cover this use-case, and if possible, I also try to make a solution for the freshly made broken tests.

**Comment by adamluzsi** [comment] 2023-09-05 08:16
https://github.com/rack-app/rack-app/issues/50

**Comment by zero20nemvp** [comment] 2023-09-05 16:54
It took a few times of going through but I do see what is happening. As you said the scope changes after mount. Your solution of making the before block only work for the class it is defined would work well. as it would adhere to  The Principle of Least Surprise.

Having thought more about my assumption, I agree that it makes more sense that I would have to include logger into the individual mounted apps , they are effectively self contained stand alone apps so by doing it this way they are less coupled to the app they are being mounted in .

thanks again for the help , much appreciated.

**Comment by adamluzsi** [comment] 2023-09-05 17:28
Great! I'll move forward with the modifications and circle back once it's complete. Thank you for reviewing the proposal, @vidtreonou. Your insights are invaluable!

**Comment by adamluzsi** [comment] 2023-09-06 23:17
I've implemented the change and released a new version. After recreating the user scenario you outlined in our example app, I confirmed the issue one more time. Then upgrading to the latest version of rack-app resolved it. @vidtreonou, could you also check on your end? Please ensure you're using the latest rack-app, currently v9.

**Comment by zero20nemvp** [comment] 2023-09-07 06:57
Hey @adamluzsi , thanks for the update, I will update the modular branch in the example project and verify this.

**Comment by adamluzsi** [comment] 2023-09-07 07:47
I've updated the example in the main branch to reflect the issue. @vidtreonou, 
Still, I'm eager to know if the new version meets your expectations.
I am looking forward to your feedback! 

@vidtreonou, I realize this might be coming a bit late, but I genuinely want to thank you for your time and effort in addressing the recent issues.
I can't tell you how much your friendly approach and dedication to resolving these issues mean to me. 
Your willingness to contribute so actively made me so happy. Thank you immensely!

**Comment by zero20nemvp** [comment] 2023-09-07 11:36
Hey @adamluzsi , thanks for the amazing feedback, it truly appreciated and really motivating.

Ok so I ran the code on the modular branch and verified the error , then ran bundle tp  updated to version 9 , when I ran it again it all worked perfectly! I then updated my current project and then 💥  my issue we nt away! 

@adamluzsi  , You have been responsive and helpful  so it has been and a pleasure to help.!

I am late to the project but for me it is proof that good software is easy to understand, fun to use and is not bloated! , so if can help in anyway moving forward, shout!

**Closed as completed** 2023-09-07 11:37 UTC

**Comment by adamluzsi** [comment] 2023-09-07 11:47
Continue doing what you've already excelled at, and please alert me if you come across any unexpected behavior. I've worked diligently to simplify the API and employed TDD throughout the project's design. However, a fresh perspective is always invaluable!
